# Generated by Django 4.2 on 2024-11-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registercourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
