# Generated by Django 4.2 on 2024-11-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0004_farmers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
