# Generated by Django 4.2 on 2024-11-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0007_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('hours', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Registercourses',
        ),
    ]
