# Generated by Django 4.2 on 2024-11-27 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0008_register_courses_delete_registercourses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
