# Generated by Django 4.2 on 2024-11-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0009_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
